# Generated by scripts/bump.sh v0.5.0 -- edit the script, not this file.
class MstreamPlayer < Formula
  desc "Terminal player and headless server-audio engine for mStream"
  homepage "https://github.com/IrosTheBeggar/mstream-terminal-player"
  version "0.5.0"
  license "GPL-3.0-only"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.5.0/mstream-player-darwin-arm64"
      sha256 "c7d1b57c137245f1d298289a7f6bf361fefff80e199f0d328e6878e033c82840"
    end
    on_intel do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.5.0/mstream-player-darwin-x64"
      sha256 "1dd6abac554974241c800578b5f123161deea0b2b567db6156a1840435501851"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.5.0/mstream-player-linux-x64"
      sha256 "a41fa4938dca958bf567461db54e9384b1bf1a3a65e16c9491ac7cd32c2c8566"
    end
    on_arm do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.5.0/mstream-player-linux-arm64"
      sha256 "65f0e65cd40585d9a92d0988d4585d62736f6c97f8412f6d70bae1655cd48ab7"
    end
  end

  def install
    bin.install Dir["mstream-player-*"].first => "mstream-player"
    chmod 0755, bin/"mstream-player"
  end

  def caveats
    return unless OS.linux?

    <<~EOS
      The Linux build needs ALSA at runtime:
        sudo apt install libasound2   (or your distro's equivalent)
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mstream-player --version")
  end
end
