# Generated by scripts/bump.sh v0.12.1 -- edit the script, not this file.
class MstreamPlayer < Formula
  desc "Terminal player and headless server-audio engine for mStream"
  homepage "https://github.com/IrosTheBeggar/mstream-terminal-player"
  version "0.12.1"
  license "GPL-3.0-only"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.12.1/mstream-player-darwin-arm64"
      sha256 "6d24d3a57abb036a6aa58dc75878917124271d78befaf8000c8231efa9c8b847"
    end
    on_intel do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.12.1/mstream-player-darwin-x64"
      sha256 "467d370ec219d80d42cc1a03cdd490d879af494888a837ff2b2970130c5b8b06"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.12.1/mstream-player-linux-x64"
      sha256 "d101cc5b088df814f9fa72352ff8a851e6d1956ee8c6344e31e80c4c71c82e2e"
    end
    on_arm do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.12.1/mstream-player-linux-arm64"
      sha256 "ddc815ca1fcfb9d8fefe2273d47b2daff5fee5139733d7a870d8dfb57d27092d"
    end
  end

  def install
    bin.install Dir["mstream-player-*"].first => "mstream-player"
    chmod 0755, bin/"mstream-player"
  end

  def caveats
    return unless OS.linux?

    <<~EOS
      The Linux build needs ALSA at runtime:
        sudo apt install libasound2   (or your distro's equivalent)
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mstream-player --version")
  end
end
