# Generated by scripts/bump.sh v0.1.0 -- edit the script, not this file.
class MstreamPlayer < Formula
  desc "Terminal player and headless server-audio engine for mStream"
  homepage "https://github.com/IrosTheBeggar/mstream-terminal-player"
  version "0.1.0"
  license "GPL-3.0-only"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.1.0/mstream-player-darwin-arm64"
      sha256 "3878d1aed4c47564ae3a85b676f5a9fc59cd580ef290a4acef08f6846cfdb8a7"
    end
    on_intel do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.1.0/mstream-player-darwin-x64"
      sha256 "4a52ccf354717651dc4b851ddbbd6a6df599342f42620ce13871cfe02107e61a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.1.0/mstream-player-linux-x64"
      sha256 "5182e8dabe56339aca51d8ba833c2ddd9061bf72a701b04bd0b17d77471986d7"
    end
    on_arm do
      url "https://github.com/IrosTheBeggar/mstream-terminal-player/releases/download/v0.1.0/mstream-player-linux-arm64"
      sha256 "89b9f0ced09597261ff7c57362c8eed6da505706608d099789238c3a3b2fd35e"
    end
  end

  def install
    bin.install Dir["mstream-player-*"].first => "mstream-player"
    chmod 0755, bin/"mstream-player"
  end

  def caveats
    return unless OS.linux?

    <<~EOS
      The Linux build needs ALSA at runtime:
        sudo apt install libasound2   (or your distro's equivalent)
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mstream-player --version")
  end
end
