#!/bin/sh
# Regenerates Formula/mstream-player.rb from a release's manifest.json.
#
#   scripts/bump.sh v0.1.0
#
# The formula is generated, never hand-edited: the player repo's release
# workflow runs this after each tag, so the file must come out of one
# template or the two would drift. The hashes come from the manifest the
# release publishes beside its binaries.
set -eu

tag="${1:?usage: bump.sh vX.Y.Z}"
version="${tag#v}"
repo="IrosTheBeggar/mstream-terminal-player"
base="https://github.com/${repo}/releases/download/${tag}"

manifest=$(mktemp)
trap 'rm -f "${manifest}"' EXIT INT TERM
if command -v curl >/dev/null 2>&1; then
    curl -fsSL -o "${manifest}" "${base}/manifest.json"
else
    wget -qO "${manifest}" "${base}/manifest.json"
fi

sha() {
    grep -o "\"file\": \"mstream-player-${1}\", \"sha256\": \"[0-9a-f]*\"" "${manifest}" \
        | grep -o '[0-9a-f]\{64\}'
}

darwin_arm=$(set -e; sha darwin-arm64)
darwin_x64=$(set -e; sha darwin-x64)
linux_x64=$(set -e; sha linux-x64)
linux_arm=$(set -e; sha linux-arm64)
for hash in "${darwin_arm}" "${darwin_x64}" "${linux_x64}" "${linux_arm}"; do
    case "${hash}" in
        "" | *[!0-9a-f]*)
            echo "manifest.json is missing a hash — refusing to write the formula" >&2
            exit 1
            ;;
    esac
done

scriptdir=$(dirname "${0}")
formula="${scriptdir}/../Formula/mstream-player.rb"
cat >"${formula}" <<FORMULA
# Generated by scripts/bump.sh ${tag} -- edit the script, not this file.
class MstreamPlayer < Formula
  desc "Terminal player and headless server-audio engine for mStream"
  homepage "https://github.com/IrosTheBeggar/mstream-terminal-player"
  version "${version}"
  license "GPL-3.0-only"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "${base}/mstream-player-darwin-arm64"
      sha256 "${darwin_arm}"
    end
    on_intel do
      url "${base}/mstream-player-darwin-x64"
      sha256 "${darwin_x64}"
    end
  end

  on_linux do
    on_intel do
      url "${base}/mstream-player-linux-x64"
      sha256 "${linux_x64}"
    end
    on_arm do
      url "${base}/mstream-player-linux-arm64"
      sha256 "${linux_arm}"
    end
  end

  def install
    bin.install Dir["mstream-player-*"].first => "mstream-player"
    chmod 0755, bin/"mstream-player"
  end

  def caveats
    return unless OS.linux?

    <<~EOS
      The Linux build needs ALSA at runtime:
        sudo apt install libasound2   (or your distro's equivalent)
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mstream-player --version")
  end
end
FORMULA
echo "Formula/mstream-player.rb -> ${version}"
